### ISSUE TITLE
Tr. Samson "mission" softlock

### ISSUE THREAD

**Issue by PennyCLMU** [OpenSauce04/EpiphanyIssues#75] opened 2023-08-03 20:59 UTC
### Preamble

- [X] I either downloaded the mod by subscribing on the Steam Workshop, or I am using the official Gamebanana mirror
- [X] I am playing on v1.7.9b of The Binding of Isaac: Repentance
- [X] I have tried installing the Mod Error Container mod before filing this issue

### What Happened?

After wave 6 of the battle to unlock Tr. Samson, the game spawned a chest instead of continuing onwards to waves 7 and 8, leaving me softlocked. Leaving the run and re-entering spawned a curse room door, which led me back to the third challenge room, adn I could re-enter the trapdoor and start anew except it starts from wave 7. Very likely to be some sort of incompatibility with a mod. Note: Did *not* have unlock bypass active

### Screenshots

I wish I could take screenshots but it'd be more of a video thing.

### Steps to Reproduce the Issue

Best thing I can assume is to attemp the Tr. Samson unlock, from a fresh save of Epiphany and from a save with Tr. Samson already unlocked.

### Diagnostics Information

[EpiphanyDiagnostics.tar.gz](https://github.com/OpenSauce04/EpiphanyIssues/files/12255015/EpiphanyDiagnostics.tar.gz)

**Comment by OpenSauce04** [comment] 2024-01-25 16:06
I can't recreate this in the latest release, and due to the insane number of mods you have installed and the age of the report, I can only assume that this was caused by some obscure incompatibility. I will close this issue, but if you experience it again, please make a fresh report.

**Closed by OpenSauce04** 2024-01-25 16:06 UTC
Labels: Unable to replicate, Wave 5
