### ISSUE TITLE
Compatible with MCM Chinese version

### ISSUE THREAD

**Issue by frto027** [OpenSauce04/EpiphanyIssues#39] opened 2023-01-15 16:39 UTC
**Describe the bug**
---

Hello, I maintain a localized ModConfigMenu for Chinese players, but it is detected as two different MCMs due to the large version number. Could you please add an extra condition to filter out this case?

**To Reproduce**
---

Subscribe [the localized mod config menu](https://steamcommunity.com/sharedfiles/filedetails/?id=2494192799).

**EpiphanyDiag info**
---

no need

**Screenshots**
---

![image](https://user-images.githubusercontent.com/20887940/212551682-e343606d-016d-46e5-848d-b17fa9892046.png)

**Version information:** 
---
 - Installed wave number: Wave 4 
 - Version number: 4.21

**Additional context**
---

The file `epiphany_scripts\scripts\detect_double_mcm.lua` may need to be changed. The localized mcm can be detected by `ModConfigMenu.i18n == "Chinese"`.
```lua
Epiphany:AddCallback(ModCallbacks.MC_POST_RENDER, function()
  if ModConfigMenu and not ModConfigMenu.i18n then
    if  ModConfigMenu.Version >= 106 -- MCM Pure
    and ModConfigMenuPopupGfx ~= nil then -- MCM Continuted
      Isaac.RenderText("You have two different versions of Mod Config Menu installed.", 60, 100, 255, 0, 0, 255)
      Isaac.RenderText("Please uninstall one of them, otherwise major bugs will occur", 60, 110, 255, 0, 0, 255)

    end
  end
end)
```

**Comment by OpenSauce04** [comment] 2023-01-22 16:33
This appears to be caused by the Chinese version of MCM using an outdated version of MCM as its base. The author said that you can use some kind of "Pure mode" in the settings to make it level with the current version of MCM. No idea why this wouldn't just be the default

**Comment by OpenSauce04** [comment] 2023-01-22 18:11
This issue has been fixed in v4.24

**Closed** 2023-01-22 18:11 UTC
Labels: Bug, Wave 4, Mod compatibility, Fixed

**Comment by frto027** [comment] 2023-01-23 03:12
Thank you. I'm the author of this MCM version. In fact I fixed a lot of things on piber's MCM code to support the repentance. In `pure mode`, it is similar to `Mod Config Memu Pure`. It will not create `ModConfigMenuPopupGfx`, so it is detected as MCM Pure by this mod. But I'm not sure if the deletion under `pure mode` will cause some mods to be incompatible, so I didn't enable this option by default. If everyone uses MCM Pure as the MCM version in the future, then this option can be enabled by default.

**Comment by OpenSauce04** [comment] 2023-01-23 11:05
MCM Continued doesn't actually work anymore if you didn't know
